public enum Gerne {
    ACTION, ADVENTURE, ANIMATION, BIOGRAPHY, COMEDY, CRIME, DOCUMENTARY, DRAMA,
    FAMILY, FANTASY, FILM_NOIR, HISTORY, HORROR, MUSIC, MUSICAL, MYSTERY,
    ROMANCE, SCI_FI, SHORT_FILM, SPORT, SUPERHERO, THRILLER, WAR, WESTERN
}
